name: tks
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py310hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.46.3=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - args==0.1.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - clint==0.5.1
      - filelock==3.20.3
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.1
      - networkx==3.4.2
      - numpy==2.2.6
      - pandas==2.3.3
      - propcache==0.4.1
      - psutil==7.2.2
      - py-tgb==2.2.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.10.0
      - torch-geometric==2.7.0
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /Users/marco/miniconda3/envs/tks
